template_defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 20
  timeout: 60000

production:
  adapter: postgresql
  encoding: unicode
  database: life_work_prod
  username: life_work_prod_user
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: 5432
  pool: 20
  timeout: 60000

staging:
  <<: *defaults
  database: life_work_staging
  username: life_work_staging_user
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  encoding: utf8

development:
  <<: *defaults
  database: life_work_dev
  #username: life_work_user

test:
  <<: *defaults
  database: life_work_test
